// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SalesCom.Infrastructure.Data;

#nullable disable

namespace SalesCom.Infrastructure.Migrations
{
    [DbContext(typeof(SalesComDbContext))]
    [Migration("20260622111742_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("salescomdbtst")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SalesCom.Domain.Entities.Approvals.ApprovalFlow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("FlowName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("flow_name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("approval_flows", "salescomdbtst");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Approvals.ApprovalFlowLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApprovalFlowId")
                        .HasColumnType("bigint")
                        .HasColumnName("approval_flow_id");

                    b.Property<int>("ApprovalType")
                        .HasColumnType("integer")
                        .HasColumnName("approval_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("level_name");

                    b.Property<int>("LevelOrder")
                        .HasColumnType("integer")
                        .HasColumnName("level_order");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalFlowId", "LevelOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_approval_flow_levels_flow_order");

                    b.ToTable("approval_flow_levels", "salescomdbtst");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Approvals.ApprovalFlowLevelUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApprovalFlowLevelId")
                        .HasColumnType("bigint")
                        .HasColumnName("approval_flow_level_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ApprovalFlowLevelId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_approval_flow_level_users_level_user");

                    b.ToTable("approval_flow_level_users", "salescomdbtst");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Approvals.ReportApproval", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApprovalFlowId")
                        .HasColumnType("bigint")
                        .HasColumnName("approval_flow_id");

                    b.Property<int>("CurrentLevelOrder")
                        .HasColumnType("integer")
                        .HasColumnName("current_level_order");

                    b.Property<DateTimeOffset>("InitiatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("initiated_at");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("initiated_by");

                    b.Property<int>("OverallStatus")
                        .HasColumnType("integer")
                        .HasColumnName("overall_status");

                    b.Property<long>("ReportSetupId")
                        .HasColumnType("bigint")
                        .HasColumnName("report_setup_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalFlowId")
                        .HasDatabaseName("ix_report_approvals_flow");

                    b.HasIndex("ReportSetupId")
                        .HasDatabaseName("ix_report_approvals_report_setup");

                    b.ToTable("report_approvals", "salescomdbtst");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Approvals.ReportApprovalDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ApprovalAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approval_at");

                    b.Property<string>("ApprovalBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("approval_by");

                    b.Property<long>("ApprovalRequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("approval_request_id");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("integer")
                        .HasColumnName("approval_status");

                    b.Property<int>("LevelOrder")
                        .HasColumnType("integer")
                        .HasColumnName("level_order");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("remarks");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalRequestId")
                        .HasDatabaseName("ix_report_approval_details_approval");

                    b.ToTable("report_approval_details", "salescomdbtst");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Auditing.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ActionType")
                        .HasColumnType("integer")
                        .HasColumnName("action_type");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("application_name");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("changed_by");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<string>("ChangedColumns")
                        .HasColumnType("text")
                        .HasColumnName("changed_columns");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entity_name");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("EntityName", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity");

                    b.ToTable("audit_logs", "salescomdbtst");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Auditing.LoginLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("full_name");

                    b.Property<int>("LoginStatus")
                        .HasColumnType("integer")
                        .HasColumnName("login_status");

                    b.Property<DateTimeOffset>("LoginTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("login_time");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remarks");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("login_logs", "salescomdbtst");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Channels.Channel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("channel_name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ChannelName")
                        .IsUnique()
                        .HasDatabaseName("ux_channels_channel_name");

                    b.ToTable("channels", "salescomdbtst");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.DataSources.DataSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("SourceTableName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_table_name");

                    b.Property<string>("TableDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("table_description");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("SourceTableName")
                        .IsUnique()
                        .HasDatabaseName("ux_data_sources_source_table");

                    b.ToTable("data_sources", "salescomdbtst");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Disbursement.EvDisburse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<string>("ChannelCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("channel_code");

                    b.Property<DateTimeOffset?>("DisburseAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disburse_at");

                    b.Property<int>("DisburseStatus")
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasColumnName("disburse_status");

                    b.Property<string>("EvMsisdn")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("ev_msisdn");

                    b.Property<long>("ReportRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("report_run_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ReportRunId")
                        .HasDatabaseName("ix_ev_disburse_report_run");

                    b.ToTable("ev_disburses", "salescomdbtst");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Disbursement.PosDisbursement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("DisburseAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disburse_at");

                    b.Property<int>("DumpStatus")
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasColumnName("dump_status");

                    b.Property<long>("ReportRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("report_run_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ReportRunId")
                        .HasDatabaseName("ix_pos_disbursement_report_run");

                    b.ToTable("pos_disbursements", "salescomdbtst");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Identity.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("full_name");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("mobile_no");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_users_user_id");

                    b.ToTable("users", "salescomdbtst");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Identity.UserRight", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("RightsCode")
                        .HasColumnType("integer")
                        .HasColumnName("rights_code");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RightsCode")
                        .IsUnique()
                        .HasDatabaseName("ux_user_rights_user_right");

                    b.ToTable("user_rights", "salescomdbtst");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Notifications.EmailNotification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("Bcc")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("bcc");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("Cc")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("cc");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("FromAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("from_address");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subject");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("to_address");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("email_notifications", "salescomdbtst");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Notifications.SmsNotification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("Messages")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("messages");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_number");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("sms_notifications", "salescomdbtst");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Reporting.FinalCommission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChannelCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("channel_code");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("commission_amount");

                    b.Property<string>("Msisdn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("msisdn");

                    b.Property<long>("ReportRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("report_run_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId")
                        .HasDatabaseName("ix_final_commissions_channel");

                    b.HasIndex("ReportRunId", "ChannelCode")
                        .IsUnique()
                        .HasDatabaseName("ux_final_commissions_run_channel_code");

                    b.ToTable("final_commissions", "salescomdbtst");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Reporting.ReportRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DisburseStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("disburse_status");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<long>("ReportSetupId")
                        .HasColumnType("bigint")
                        .HasColumnName("report_setup_id");

                    b.Property<DateTimeOffset>("RunDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_date");

                    b.Property<int>("RunStatus")
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasColumnName("run_status");

                    b.Property<int>("RunType")
                        .HasColumnType("integer")
                        .HasColumnName("run_type");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("TriggeredBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("triggered_by");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ReportSetupId")
                        .HasDatabaseName("ix_report_runs_report_setup");

                    b.ToTable("report_runs", "salescomdbtst");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Reporting.ReportSetup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApprovalFlowId")
                        .HasColumnType("bigint")
                        .HasColumnName("approval_flow_id");

                    b.Property<long>("ChannelTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_type_id");

                    b.Property<string>("CommissionCycle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("commission_cycle");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("Definition")
                        .HasColumnType("jsonb")
                        .HasColumnName("definition");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<TimeOnly?>("EvDisbursementTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("ev_disbursement_time");

                    b.Property<bool>("IsEvDisbursement")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ev_disbursement");

                    b.Property<bool>("IsPosDisbursement")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pos_disbursement");

                    b.Property<bool>("IsRecurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recurrent");

                    b.Property<bool>("IsReportStop")
                        .HasColumnType("boolean")
                        .HasColumnName("is_report_stop");

                    b.Property<bool>("IsSetupComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_setup_complete");

                    b.Property<int>("RecurrentType")
                        .HasMaxLength(100)
                        .HasColumnType("integer")
                        .HasColumnName("recurrent_type");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("report_name");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("report_type");

                    b.Property<DateTimeOffset?>("RunEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_end_date");

                    b.Property<DateTimeOffset?>("RunStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_start_date");

                    b.Property<string>("SmsContent")
                        .HasColumnType("text")
                        .HasColumnName("sms_content");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalFlowId");

                    b.HasIndex("ChannelTypeId");

                    b.ToTable("report_setups", "salescomdbtst");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Reporting.ReportSupportingUpload", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DbSchema")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("db_schema");

                    b.Property<string>("DbTableName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("db_table_name");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("file_name");

                    b.Property<string>("ObjectBucket")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("object_bucket");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("object_key");

                    b.Property<long>("ReportSetupId")
                        .HasColumnType("bigint")
                        .HasColumnName("report_setup_id");

                    b.Property<int?>("RowCount")
                        .HasColumnType("integer")
                        .HasColumnName("row_count");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("uploaded_by");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ReportSetupId")
                        .HasDatabaseName("ix_report_supporting_uploads_report_setup");

                    b.ToTable("report_supporting_uploads", "salescomdbtst");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Reporting.RunStage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Bucket")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bucket");

                    b.Property<int>("CleanupStatus")
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasColumnName("cleanup_status");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("document_type");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTimeOffset>("FileGeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("file_generated_at");

                    b.Property<string>("FileName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("file_name");

                    b.Property<string>("ObjectUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("object_url");

                    b.Property<string>("OutputTableName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("output_table_name");

                    b.Property<long>("RunId")
                        .HasColumnType("bigint")
                        .HasColumnName("run_id");

                    b.Property<int>("RunStatus")
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasColumnName("run_status");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("SqlText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sql_text");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_run_stages_run");

                    b.ToTable("run_stages", "salescomdbtst");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Reporting.SectionWiseReportSql", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ReportSetupId")
                        .HasColumnType("bigint")
                        .HasColumnName("report_setup_id");

                    b.Property<string>("SqlText")
                        .HasColumnType("text")
                        .HasColumnName("sql_text");

                    b.Property<int>("StageOrder")
                        .HasColumnType("integer")
                        .HasColumnName("stage_order");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ReportSetupId", "StageOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_section_wise_report_sqls_setup_order");

                    b.ToTable("section_wise_report_sqls", "salescomdbtst");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Approvals.ApprovalFlowLevel", b =>
                {
                    b.HasOne("SalesCom.Domain.Entities.Approvals.ApprovalFlow", "ApprovalFlow")
                        .WithMany("ApprovalFlowLevels")
                        .HasForeignKey("ApprovalFlowId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("ApprovalFlow");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Approvals.ApprovalFlowLevelUser", b =>
                {
                    b.HasOne("SalesCom.Domain.Entities.Approvals.ApprovalFlowLevel", "ApprovalFlowLevel")
                        .WithMany("ApprovalLevelUsers")
                        .HasForeignKey("ApprovalFlowLevelId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("SalesCom.Domain.Entities.Identity.User", "User")
                        .WithMany("ApprovalFlowLevelUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("ApprovalFlowLevel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Approvals.ReportApproval", b =>
                {
                    b.HasOne("SalesCom.Domain.Entities.Approvals.ApprovalFlow", null)
                        .WithMany()
                        .HasForeignKey("ApprovalFlowId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("SalesCom.Domain.Entities.Reporting.ReportSetup", "ReportSetup")
                        .WithMany()
                        .HasForeignKey("ReportSetupId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("ReportSetup");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Approvals.ReportApprovalDetail", b =>
                {
                    b.HasOne("SalesCom.Domain.Entities.Approvals.ReportApproval", "ApprovalRequest")
                        .WithMany("ApprovalDecisions")
                        .HasForeignKey("ApprovalRequestId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("ApprovalRequest");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Disbursement.EvDisburse", b =>
                {
                    b.HasOne("SalesCom.Domain.Entities.Reporting.ReportRun", "ReportRun")
                        .WithMany()
                        .HasForeignKey("ReportRunId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("ReportRun");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Disbursement.PosDisbursement", b =>
                {
                    b.HasOne("SalesCom.Domain.Entities.Reporting.ReportRun", "ReportRun")
                        .WithMany()
                        .HasForeignKey("ReportRunId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("ReportRun");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Identity.UserRight", b =>
                {
                    b.HasOne("SalesCom.Domain.Entities.Identity.User", "User")
                        .WithMany("UserRights")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Reporting.FinalCommission", b =>
                {
                    b.HasOne("SalesCom.Domain.Entities.Channels.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("SalesCom.Domain.Entities.Reporting.ReportRun", "ReportRun")
                        .WithMany()
                        .HasForeignKey("ReportRunId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("ReportRun");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Reporting.ReportRun", b =>
                {
                    b.HasOne("SalesCom.Domain.Entities.Reporting.ReportSetup", "ReportSetup")
                        .WithMany()
                        .HasForeignKey("ReportSetupId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("ReportSetup");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Reporting.ReportSetup", b =>
                {
                    b.HasOne("SalesCom.Domain.Entities.Approvals.ApprovalFlow", "ApprovalFlow")
                        .WithMany()
                        .HasForeignKey("ApprovalFlowId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("SalesCom.Domain.Entities.Channels.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelTypeId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("ApprovalFlow");

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Reporting.ReportSupportingUpload", b =>
                {
                    b.HasOne("SalesCom.Domain.Entities.Reporting.ReportSetup", "ReportSetup")
                        .WithMany()
                        .HasForeignKey("ReportSetupId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("ReportSetup");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Reporting.RunStage", b =>
                {
                    b.HasOne("SalesCom.Domain.Entities.Reporting.ReportRun", "ReportRun")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("ReportRun");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Reporting.SectionWiseReportSql", b =>
                {
                    b.HasOne("SalesCom.Domain.Entities.Reporting.ReportSetup", "ReportSetup")
                        .WithMany()
                        .HasForeignKey("ReportSetupId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("ReportSetup");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Approvals.ApprovalFlow", b =>
                {
                    b.Navigation("ApprovalFlowLevels");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Approvals.ApprovalFlowLevel", b =>
                {
                    b.Navigation("ApprovalLevelUsers");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Approvals.ReportApproval", b =>
                {
                    b.Navigation("ApprovalDecisions");
                });

            modelBuilder.Entity("SalesCom.Domain.Entities.Identity.User", b =>
                {
                    b.Navigation("ApprovalFlowLevelUsers");

                    b.Navigation("UserRights");
                });
#pragma warning restore 612, 618
        }
    }
}
